name: dart_libxl
version: 1.0.0
description: >-
  The package wraps the libxl library methods. Provides a 
  convenient API for creating xls files of any complexity. 
  Most of the libxl methods are implemented.
author: Vitaly Stekolschikov <v.a.stekolschikov@gmail.com>
dependencies:
  build_tools:
    git: https://github.com/mezoni/build_tools.git
  ccompilers: any
  lists: any
  patsubst:
    git: https://github.com/mezoni/patsubst