name: dart_libxl
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: vts <email@example.com>

environment:
  sdk: '>=2.0.0-dev.68.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^1.0.0
  grinder: ^0.8.3
  recase: any